version: "3"
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - emprendapp
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server/
    env_file: ./server/config/${ENV}.env
    environment:
      - NODE_ENV=${ENV}
    ports:
      - "5000:5000"
    networks:
      - emprendapp
    depends_on:
      - emprendimientos_db
    command: bash -c 'while !</dev/tcp/emprendimientos_db/3306; do sleep 1; done; chmod +x ./entrypoint.sh; ./entrypoint.sh'
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
  emprendimientos_db:
    image: mysql:5.7.20
    env_file: ./server/config/${ENV}.env
    ports:
      - "3306:3306"
    networks:
      - emprendapp
    volumes:
      - mysql:/var/lib/mysql
networks:
  emprendapp:
    driver: bridge
volumes:
  mysql:
    driver: local
