version: "3"
services:
  react-app:
    image: react-app-production:${ENV}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - emprendapp
    volumes:
      - caddy-data:/data
      - caddy-config:/config
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./server/config/${ENV}.env
    environment:
      - NODE_ENV=${ENV}
    ports:
      - "5000:5000"
    networks:
      - emprendapp
    depends_on:
      - emprendimientos_db
    command: bash -c 'while !</dev/tcp/emprendimientos_db/3306; do sleep 1; done; chmod +x ./entrypoint.sh; ./entrypoint.sh'
  emprendimientos_db:
    image: mysql:5.7.20
    env_file: ./server/config/${ENV}.env
    ports:
      - "3306:3306"
    networks:
      - emprendapp
    volumes:
      - mysql:/var/lib/mysql
networks:
  emprendapp:
    driver: bridge
volumes:
  mysql:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
