export const FETCH_EMPRENDIMIENTOS = 'FETCH_EMPRENDIMIENTOS';
export const FILTER_EMPRENDIMIENTOS_BY_CATEGORY =
  'FILTER_EMPRENDIMIENTOS_BY_CATEGORY';
export const ADD_EMPRENDIMIENTO = 'ADD_EMPRENDIMIENTO';
export const DELETE_EMPRENDIMIENTO = 'DELETE_EMPRENDIMIENTO';
export const EDIT_EMPRENDIMIENTO = 'EDIT_EMPRENDIMIENTO';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
